name: znedi3 & nnedi3

on: workflow_dispatch

permissions:
  actions: write
  security-events: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: '3.11'

    - name: Setup Envs
      run: |
        sudo apt install git build-essential nasm yasm ninja-build gh gcc-12 gcc-12-multilib g++-12 g++-12-multilib
        python -m pip install -U pip
        pip install -U cython setuptools wheel

    - name: Build
      run: |
        git clone --recursive https://github.com/sekrit-twc/znedi3.git
        pushd znedi3
        make X86=1
        popd

        git clone https://github.com/sekrit-twc/zimg --depth 1 --shallow-submodules --recurse-submodules
        pushd zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j2
        sudo make install -j2
        popd
        rm -rf zimg

        git clone https://github.com/vapoursynth/vapoursynth.git
        git checkout R64
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr
        make -j2
        sudo make install -j2
        python setup.py sdist -d sdist
        mkdir empty
        pushd empty
        pip install vapoursynth --no-index --find-links ../sdist
        popd

        git clone --recursive https://github.com/dubhater/vapoursynth-nnedi3.git
        pushd vapoursynth-nnedi3
        ./autogen.sh
        ./configure
        make
        popd

    - name: Compress artifact
      run: |
        7z a -t7z -mx=7 znedi3-build.7z ./znedi3
        7z a -t7z -mx=7 nnedi3-build.7z ./vapoursynth-nnedi3
        mkdir result
        cp znedi3-build.7z result/znedi3-build.7z
        cp nnedi3-build.7z result/nnedi3-build.7z

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: result/*
